# Multi-Agent Framework Configuration

claude:
  # Claude Code CLI Configuration (Unified approach)
  cli_path: "claude" # Path to Claude Code CLI executable (auto-detected if not specified)

  # Model Configuration
  model: "claude-sonnet-4-20250514" # Claude model to use
  max_tokens: 4000 # Maximum tokens per request
  temperature: 0.7 # Creativity/randomness (0.0-1.0)
  timeout: 120 # Request timeout in seconds

  # Output Configuration
  use_streaming: false # Use streaming JSON output for real-time responses
  verbose_output: false # Enable verbose logging from Claude CLI

  # Rate Limiting
  min_request_interval: 1.0 # Minimum seconds between requests

  # Tools and Permissions
  allowed_tools: [] # Specific tools to allow (empty = all available)
  permission_mode: "default" # Permission mode: "default", "acceptEdits", "bypassPermissions", "plan"

  # Session Management
  enable_sessions: true # Enable conversation sessions
  max_session_history: 20 # Maximum messages per session

  # Fallback Configuration
  auto_fallback_to_mock: true # Automatically fall back to mock if CLI fails
  mock_mode: true # Force mock mode (using DirectClaudeCLI for active session)

framework:
  max_parallel_agents: 5
  default_workflow_timeout: 600 # seconds
  message_queue_size: 1000
  enable_debug_mode: true

memory:
  database_path: "data/memory.db"
  cache_dir: "data/cache"
  cache_size: 1000
  embedding_model: "all-MiniLM-L6-v2"
  embedding_dim: 384
  max_memories_per_query: 10
  consolidation_interval: 86400 # seconds (24 hours)

logging:
  level: "DEBUG"
  log_dir: "logs"
  max_log_size: 10485760 # 10MB
  max_log_files: 10
  log_agent_communications: true
  log_token_usage: true

agents:
  architect:
    name: "Architect"
    role: "System design and architecture planning"
    capabilities:
      - "system_design"
      - "api_design"
      - "database_schema"
      - "architecture_patterns"
    max_retries: 2

  developer:
    name: "Developer"
    role: "Code implementation and generation"
    capabilities:
      - "python"
      - "javascript"
      - "sql"
      - "api_implementation"
      - "algorithm_design"
    max_retries: 3

  reviewer:
    name: "Reviewer"
    role: "Code review and quality assurance"
    capabilities:
      - "code_review"
      - "security_analysis"
      - "performance_review"
      - "best_practices"
    max_retries: 2

  tester:
    name: "Tester"
    role: "Test creation and execution"
    capabilities:
      - "unit_testing"
      - "integration_testing"
      - "test_generation"
      - "coverage_analysis"
    max_retries: 2

  debugger:
    name: "Debugger"
    role: "Error analysis and fixing"
    capabilities:
      - "error_analysis"
      - "bug_fixing"
      - "stack_trace_analysis"
      - "performance_debugging"
    max_retries: 3

  documenter:
    name: "Documenter"
    role: "Documentation generation and maintenance"
    capabilities:
      - "api_documentation"
      - "code_comments"
      - "readme_generation"
      - "technical_writing"
    max_retries: 1

  optimizer:
    name: "Optimizer"
    role: "Performance and efficiency optimization"
    capabilities:
      - "performance_analysis"
      - "algorithm_optimization"
      - "memory_optimization"
      - "code_refactoring"
    max_retries: 2

workflows:
  code_generation:
    stages:
      - agent: "architect"
        action: "design" # Now matches with improved capability checking
        timeout: 60
      - agent: "developer"
        action: "implement"
        timeout: 120
      - agent: "reviewer"
        action: "review"
        timeout: 60
      - agent: "tester"
        action: "test"
        timeout: 90
      - agent: "documenter"
        action: "document"
        timeout: 45

  bug_fix:
    stages:
      - agent: "debugger"
        action: "analyze"
        timeout: 60
      - agent: "developer"
        action: "fix"
        timeout: 90
      - agent: "tester"
        action: "validate"
        timeout: 60
      - agent: "reviewer"
        action: "approve"
        timeout: 45

  optimization:
    stages:
      - agent: "optimizer"
        action: "analyze"
        timeout: 60
      - agent: "developer"
        action: "implement"
        timeout: 90
      - agent: "tester"
        action: "benchmark"
        timeout: 60
      - agent: "reviewer"
        action: "validate"
        timeout: 45
